# Generated by Django 5.0.7 on 2024-07-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
    ]
